bbs/urls.py
from django.urls import path
from . import views

app_name    = "bbs"
urlpatterns = [
    path('', views.index, name="index"),
    path('delete/<int:pk>/', views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bbs.urls")),
]

bbs/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    class Meta:
        db_table = "category"

    name = models.CharField(verbose_name="カテゴリ名",max_length=100)
    dt = models.DateTimeField(verbose_name="追加日", default=timezone.now)

    def __str__(self):
        return self.name

class Topic(models.Model):

    class Meta:
        db_table = "topic"

    category = models.ForeignKey(Category,verbose_name="カテゴリ",on_delete=models.CASCADE,null=True)


    title = models.CharField(verbose_name="タイトル", max_length=100, default="")
    comment = models.CharField(verbose_name="コメント", max_length=2000)
    price = models.IntegerField(verbose_name="金額", null=True)
    salary = models.IntegerField(verbose_name="収入", null=True)
    spending = models.IntegerField(verbose_name="支出", null=True)
    dt = models.DateTimeField(verbose_name="投稿日", default=timezone.now)


    pay_dt  =  models.DateTimeField(verbose_name="決済日")

    def __str__(self):
        return self.comment

bbs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model     = Topic
        fields   = [ "category","title","comment","price","salary","spending","pay_dt"]

bbs/views.py
from django.shortcuts import render,redirect
from django.views import View

from .models import Topic,Category
from .forms import TopicForm


from django.db.models import Q


class BbsView(View):

    def get(self, request, *args, **kwargs):

        #topics = Topic.objects.all()


        categories  = Category.objects.all()
        


        if "search" in request.GET:

            if request.GET["search"] == "" or request.GET["search"].isspace():
                return redirect("bbs:index")

            search      = request.GET["search"].replace(" ","　")
            search_list =search.split(" ")

            query       = Q()
            for word in search_list:

                query &= Q(title__contains=word)


            topics  = Topic.objects.filter(query)
        else:
            topics  = Topic.objects.all()



        chobos = []
        context = { "chobos":chobos,
                    "topics":topics,
                    "categories":categories,
                    }

        return render(request,"bbs/index.html",context)

    def post(self, request, *args, **kwargs):

        form = TopicForm(request.POST)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")

        return redirect("bbs:index")

index   = BbsView.as_view()

class BbsDeleteView(View):

    def post(self,request, pk, *args, **kwargs):

        topic = Topic.objects.filter(id=pk).first()
        topic.delete()

        return redirect("bbs:index")

delete = BbsDeleteView.as_view()

# Create your views here.

templates/bbs/index.html
{% load static %}
{% load humanize %}


<html>
<head>
    <meta charset="UTF-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!--日本語化用JS-->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>

    <link rel="stylesheet" href="{% static 'bbs/css/style.css' %}">
    <script src="{% static 'bbs/js/script.js' %}"></script>

    <style>
    .example1 {
    width: 300px;
    height: 180px;
    }
    </style>
</head>
<body>

<h1>helow world!</h1>

<img class="example1" src="{% static 'bbs/img/cat.jpeg' %}">


<form action="" method="get">
    <input type="text" name="search" placeholder="検索したいワード" value="{{ request.GET.search }}">
    <input type="submit" class="btn btn-outline-dark" value="検索">
</form>



<form action="" method="post">
    {% csrf_token %}

    <select name="category">
        <option value="">カテゴリを選んでください</option>
        {% for category in categories %}
        <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
    <input type="text" name="title" placeholder="鑑定科目を入力してください" required>
    <input type="text" name="comment" placeholder="主な用途を入力してください" required>
    <input type="number" name="salary" placeholder="収入金額を入力してください" required>
    <input type="number" name="spending" placeholder="支出金額を入力してください" required>
    <input type="number" name="price" placeholder="残高を入力してください" required>
    <input id="pay_dt" type="text" name="pay_dt" readonly>
    <input class="btn btn-success" type="submit" value="投稿">
</form>


{% if topics %}
<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <td class="text-center">id</td>
            <td class="text-center">カテゴリ</td>
            <td class="text-center">鑑定項目</td>
            <td class="text-center">主な用途</td>
            <td class="text-center">収入金額</td>
            <td class="text-center">支出金額</td>
            <td class="text-center">残高</td>
            <td class="text-center">登録日</td>
            <td class="text-center">決算日</td>
            <td></td>
        </tr>
    </thead>

    <tbody>
        {#{% load mathfilters %} #}
    {% for topic in topics %}
    <tr>
        <td>{{ topic.id }}</td>
        <td>{{ topic.category|default:"未分類" }}</td>
        <td>{{ topic.title }}</td>
        <td>{{ topic.comment }}</td>
        <td>{{ topic.price|default:"0"|intcomma }}</td>
        <td>{{ topic.salary|default:"0"|intcomma }}</td>
        <td>{{ topic.spending|default:"0"|intcomma }}</td>
        {# <td>{{ topic.salary|sub:topic.spending|price }}</td> #}
        <td>{{ topic.dt }}</td>
        <td>{{ topic.pay_dt }}</td>
        <td>
           <form action="{% url 'bbs:delete' topic.id %}" method="POST">
               {% csrf_token %}
               <input class="btn btn-outline-dark" type="submit" value="削除">
           </form>
        </td>
    </tr>
    {% endfor %}


    </tbody>

</table>
    {% endif %}

<div style="border:solid 1px orange;">
    <div></div>
    <div></div>
</div>


<form action="" method="GET">
    <input type="text" name="search" placeholder="キーワードを入力してください">
    <input type="text" name="category" placeholder="カテゴリを入力してください">
    <input class="btn btn-success" type="submit" value="送信">

</form>

<form action="" method="POST">
    {% csrf_token %}
    <input type="text" name="comment" placeholder="コメントを入力してください">
    <input type="text" name="anti" placeholder="反対コメントを入力してください">
    <input type="submit" value="送信">

</form>

<p>{{ chobo }}</p>

    {% for chobo in chobos %}
<div style="border:solid 0.2rem orange; padding:0.25rem;">
<div>{{ chobo.id }}</div>
<div>{{ chobo.title }}</div>
<div>{{ chobo.price }}</div>
</div>
    {% endfor %}

</body>

</html>